function generateR() {
    var afrmtR = [ 
    '<img src="images/imgRight/right1.png">',
    '<img src="images/imgRight/right2.png">', 
    '<img src="images/imgRight/right3.png">', 
    '<img src="images/imgRight/right4.png">',
    '<img src="images/imgRight/right5_Монтажная область 1.png">', 
    '<img src="images/imgRight/right6_Монтажная область 1.png">',
    '<img src="images/imgRight/right7_Монтажная область 1.png">',
    '<img src="images/imgRight/right8_Монтажная область 1.png">',
    '<img src="images/imgRight/right9_Монтажная область 1.png">',
    '<img src="images/imgRight/right10_Монтажная область 1.png">',
    '<img src="images/imgRight/right11_Монтажная область 1.png">',
    '<img src="images/imgRight/right12_Монтажная область 1.png">',
    '<img src="images/imgRight/right13_Монтажная область 1.png">',
    '<img src="images/imgRight/right14_Монтажная область 1.png">',
    '<img src="images/imgRight/right15_Монтажная область 1.png">',
    '<img src="images/imgRight/right16_Монтажная область 1.png">',
    '<img src="images/imgRight/right17_Монтажная область 1.png">',
    '<img src="images/imgRight/right18_Монтажная область 1.png">',
    '<img src="images/imgRight/right19_Монтажная область 1.png">',
    '<img src="images/imgRight/right20_Монтажная область 1.png">',
    '<img src="images/imgRight/right21_Монтажная область 1.png">',
    '<img src="images/imgRight/right22_Монтажная область 1.png">',
    '<img src="images/imgRight/right23_Монтажная область 1.png">',
    '<img src="images/imgRight/right24_Монтажная область 1.png">',
    '<img src="images/imgRight/right25_Монтажная область 1.png">',
    '<img src="images/imgRight/right26_Монтажная область 1.png">',
    '<img src="images/imgRight/right27_Монтажная область 1.png">',
    '<img src="images/imgRight/right28_Монтажная область 1.png">',
    '<img src="images/imgRight/right29_Монтажная область 1.png">',
    '<img src="images/imgRight/right30_Монтажная область 1.png">',
    '<img src="images/imgRight/right31_Монтажная область 1.png">',
    '<img src="images/imgRight/right32_Монтажная область 1.png">',
    '<img src="images/imgRight/right33_Монтажная область 1.png">',
    '<img src="images/imgRight/right34_Монтажная область 1.png">',
    '<img src="images/imgRight/right35_Монтажная область 1.png">',
    '<img src="images/imgRight/right36_Монтажная область 1.png">',  
];

var r=document.querySelector(".div4");
r.innerHTML=afrmtR[Math.floor(Math.random()*afrmtR.length)];
}